---
title: "STL Project"
author: "Lu"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r Library, message=FALSE, include=FALSE}
rm(list=ls())
#Load Packages----
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(emmeans)

```


## Clean and check data:

The first step is to clean and check the data.

```{r}
#Import data to R
STL_2018_2022 <- read_csv("Desktop/data/STL_2018-2022-5-15.csv", 
                          col_types = cols(LabNo = col_character(),Type = col_character(), 
                                           NO3W = col_double(), B = col_double()))

# Check errors
parsing_failures <- problems(STL_2018_2022)
parsing_failures

#Group an exclude years 2017 and 2023----
#Filter unused years
by_years <- STL_2018_2022 %>% 
  group_by (Year) %>% 
  filter (Year<2023, 2017<Year)
by_years

# Grouping by year----
g_years <- by_years %>% 
  count(Year)
g_years

```

## Plot 

The number of total samples received during 2018-2022.

```{r}
p_years <-ggplot (g_years, aes(x= Year, y=n)) + geom_bar (stat = "identity") + 
  geom_text(aes(label = n, vjust = 2)) + theme_minimal() 
p_years

```


```{r}
#Percentage stacked barplot -> Each sector with percentage----
percent_df <- STL_2018_2022 %>%
  count(Year, Sector) %>%  
  group_by(Year) %>%
  filter (Year<2023, 2017<Year) %>%
  mutate(pct= prop.table(n) * 100) %>%
  drop_na() %>%
  ggplot() + aes(Year, pct, fill=Sector) +
  geom_bar(stat="identity") +
  ylab("Number of Samples") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),
            position=position_stack(vjust=0.5)) +
  ggtitle(" Percentage of samples per Sector from 2018-2022") +
  theme_bw()

percent_df
```

```{r}
# 4 separate graphs -> Each sector its own graphs apart to check easy visualize the change over time

#---- Date in axis, samples vs months by sector = County
as.data.frame(STL_2018_2022) %>%
  mutate(Month = month.abb[lubridate::month(date, label = TRUE)],
         Year = lubridate::year(date))

time_df1 <- STL_2018_2022 %>%
  select(date, Month, Year, Sector)%>%
  group_by(Month, Year, Sector) %>%
  filter (2017<Year, Year<2023, Sector == "County")%>%
  mutate(Month = month.abb[lubridate::month(date, label = TRUE)],
         Year = lubridate::year(date), sort=FALSE) %>% # Months in letters
  summarise(n= n())

#plot the samples over
p_time <-  ggplot (time_df1, aes (x=Month, y=n, group=Year, color=factor(Year) )) + geom_line(na.rm = TRUE) +
  scale_color_brewer(palette="Paired")+
  scale_x_discrete(limits = month.abb)   +
  theme_minimal()
p_time

```

```{r}
#plot the samples over
p_time <-  ggplot (time_df1, aes (x=Month, y=n, group=Year, color=factor(Year) )) + geom_line(na.rm = TRUE) +
  scale_color_brewer(palette="Paired")+
  scale_x_discrete(limits = month.abb)   +
  theme_minimal()
p_time
```


