---
title: "STL Project"
output:
  output: html_document

---

This is my first notebook project in R. I will be exploring the following mocking soil laboratory dataset.
```{r include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
library(rmarkdown)

STL_2018_2022 <- read_csv("~/Downloads/STL_2018-2022.csv", 
                          col_types = cols(LabNo = col_character(),Type = col_character(), 
                                           NO3W = col_double(), B = col_double()))

```



```{r echo=TRUE}
#Group an exclude years 2017 and 2023----
#Filter unused years
by_years <- STL_2018_2022 %>% 
  group_by (Year) %>% 
  filter (Year<2023, 2017<Year)
by_years

# Grouping by year----
g_years <- STL_2018_2022 %>% 
  #group_by (Year) %>% 
  filter (Year<2023, 2017<Year) %>% 
  count(Year)
g_years

# For testing
t_years <- STL_2018_2022 %>% 
  #group_by (Year) %>% 
  filter (Year<2023, 2017<Year) 
#%>% 
#count(Year)
t_years

#graph the Evolution of samples per time 
p_years <-ggplot (g_years, aes(x= Year, y=n)) + geom_bar (stat = "identity") + 
  geom_text(aes(label = n, vjust = 2)) + theme_minimal() 
p_years
```
